# -*- coding: utf-8 -*-
"""fhmm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJvYD8CpTGnGeoyS_7e0TirTt_IIl4oW
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install hmmlearn scikit-learn

import tensorflow as tf

print("GPU:", tf.config.list_physical_devices('GPU'))

import os
import numpy as np
import json
from hmmlearn import hmm
from sklearn.metrics import mean_absolute_error, f1_score

DATA_DIR = "/content/drive/MyDrive/FYP/phase3"

APPLIANCES = ["toaster", "kettle", "computer", "lamp"]

train_houses = list(range(1, 17))   # 1–16
test_houses  = list(range(17, 21))  # 17–20

def load_data(appliance, houses, max_samples=5000):
    X_all, y_all = [], []

    for file in os.listdir(DATA_DIR):
        if appliance not in file or not file.endswith(".npz"):
            continue

        house_id = int(file.split("_")[0].replace("house", ""))
        if house_id not in houses:
            continue

        path = os.path.join(DATA_DIR, file)
        data = np.load(path)

        print(f"Loading: {file}")

        X = data["X"]
        y = data["y"]

        X = X[:max_samples]
        y = y[:max_samples]

        X_all.append(X)
        y_all.append(y)

    return np.vstack(X_all), np.hstack(y_all)

results = {}

for app in APPLIANCES:

    print("\n====================")
    print("Processing:", app)
    print("====================")

    # =========================
    # LOAD DATA
    # =========================
    X_train, y_train = load_data(app, train_houses)
    X_test, y_test   = load_data(app, test_houses)

    print("Train:", X_train.shape, "Test:", X_test.shape)

    # =========================
    # FEATURE (mean of window)
    # =========================
    X_train_feat = np.mean(X_train, axis=1).reshape(-1,1)
    X_test_feat  = np.mean(X_test, axis=1).reshape(-1,1)

    # =========================
    # FHMM (Gaussian HMM)
    # =========================
    model = hmm.GaussianHMM(
        n_components=4,
        covariance_type="diag",
        n_iter=100,   # ✅ as requested
        tol=1e-3,
        random_state=42
    )

    model.fit(X_train_feat)

    # =========================
    # PREDICT STATES
    # =========================
    states = model.predict(X_test_feat)

    # =========================
    # STATE → ON/OFF
    # =========================
    means = model.means_.flatten()
    sorted_idx = np.argsort(means)

    state_map = {}
    for i, s in enumerate(sorted_idx):
        state_map[int(s)] = 0 if i < len(sorted_idx)//2 else 1

    y_pred = np.array([state_map.get(int(s), 0) for s in states])

    # =========================
    # GROUND TRUTH
    # =========================
    threshold = np.percentile(y_train, 50)
    y_true = (y_test > threshold).astype(int)

    # =========================
    # EVALUATION
    # =========================
    mae = mean_absolute_error(y_true, y_pred)
    f1  = f1_score(y_true, y_pred)

    print("State means:", means)
    print("State map:", state_map)
    print("MAE:", mae)
    print("F1 Score:", f1)

    results[app] = {"MAE": mae, "F1": f1}

    # =========================
    # SAVE FOR RASPBERRY PI
    # =========================
    save_data = {
        "means": means.tolist(),
        "state_map": state_map,
        "threshold": float(threshold)
    }

    with open(f"/content/{app}_fhmm.json", "w") as f:
        json.dump(save_data, f)

from google.colab import files

for app in APPLIANCES:
    files.download(f"/content/{app}_fhmm.json")

print("\n========= FINAL FHMM RESULTS =========")

for app, res in results.items():
    print(f"\n{app.upper()}")
    print("MAE:", res["MAE"])
    print("F1 :", res["F1"])