version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883" # MQTT
      - "9001:9001" # Websockets (for Node-RED dashboard)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  influxdb:
    image: influxdb:2.6
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb2:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: max
      DOCKER_INFLUXDB_INIT_PASSWORD: Maxinelim28!
      DOCKER_INFLUXDB_INIT_ORG: SmartEnergy
      DOCKER_INFLUXDB_INIT_BUCKET: energy_data
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ccRQCClqAZnYv2CAyX8lEklwlv0G8HFj5dobSuRwOD-Iqz0n91wlf9vLR9RplmMqcmVxJZP0l8ZhjskXJOb2QQ==
  grafana:
    image: grafana/grafana-enterprise:9.3.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    depends_on:
      - influxdb
  node-red:
    image: nodered/node-red:3.0.2
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red/data:/data
    depends_on:
      - mqtt
      - influxdb
