# -*- coding: utf-8 -*-
"""Classifier D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qqxuR79syHReeYe_eHDvkXiycGueTr4F
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import tensorflow as tf
import os
import json
import gc

from sklearn.metrics import f1_score, mean_absolute_error
from sklearn.model_selection import train_test_split

MODEL_PATH = "/content/drive/MyDrive/FYP/models"
DATA_PATH = "/content/drive/MyDrive/FYP/phase3"

train_houses = list(range(1, 17))
test_houses = list(range(17, 21))

os.makedirs(MODEL_PATH, exist_ok=True)

MAX_SAMPLES = 8000

def load_seq2point_predictions(app, X):
    model = tf.keras.models.load_model(
        f"{MODEL_PATH}/{app}_seq2point_final.h5",
        compile=False
    )
    return model.predict(X, verbose=0).flatten()


def load_data(app, houses):
    X, y, seq = [], [], []

    for house in houses:
        path = f"{DATA_PATH}/house{house}_{app}_seq2point.npz"
        if not os.path.exists(path):
            continue

        data = np.load(path)
        X_tmp = data['X']
        y_tmp = data['y']

        seq_tmp = load_seq2point_predictions(app, X_tmp)

        if len(X_tmp) > MAX_SAMPLES:
            idx = np.random.choice(len(X_tmp), MAX_SAMPLES, replace=False)
            X_tmp = X_tmp[idx]
            y_tmp = y_tmp[idx]
            seq_tmp = seq_tmp[idx]

        X.append(X_tmp)
        y.append(y_tmp)
        seq.append(seq_tmp)

    return np.concatenate(X), np.concatenate(y), np.concatenate(seq)

def build_model(input_length, channels):
    model = tf.keras.Sequential([
        tf.keras.layers.Conv1D(64, 5, activation='relu', input_shape=(input_length, channels)),
        tf.keras.layers.MaxPooling1D(2),

        tf.keras.layers.Conv1D(128, 3, activation='relu'),
        tf.keras.layers.MaxPooling1D(2),

        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.3),

        tf.keras.layers.Dense(1, activation='sigmoid')
    ])

    return model

def focal_loss(alpha=0.75, gamma=2.0):
    def loss(y_true, y_pred):
        y_pred = tf.clip_by_value(y_pred, 1e-7, 1 - 1e-7)
        pt = tf.where(tf.equal(y_true, 1), y_pred, 1 - y_pred)
        return -tf.reduce_mean(alpha * tf.pow(1 - pt, gamma) * tf.math.log(pt))
    return loss

def train_classifier(APP):

    print("\n===== TRAINING:", APP, "=====")

    # =========================
    # SPECIAL CASE: KETTLE
    # =========================
    if APP == "kettle":

        print("Using STABLE kettle mode")

        X_train, y_train, _ = load_data(APP, train_houses)
        X_test, y_test, _ = load_data(APP, test_houses)

        X_train = X_train[..., np.newaxis]
        X_test = X_test[..., np.newaxis]

        print("y_train min:", np.min(y_train))
        print("y_train max:", np.max(y_train))

        # ORIGINAL WORKING THRESHOLD
        threshold = np.max(y_train) * 0.1

        y_train_bin = (y_train > threshold).astype(int)
        y_test_bin = (y_test > threshold).astype(int)

        print("Threshold:", threshold)
        print("ON ratio:", np.mean(y_train_bin))

        # ✅ SAFE CLASS WEIGHT
        on_ratio = np.mean(y_train_bin)
        class_weights = {
            0: 1.0,
            1: min(8, 1 / (on_ratio + 1e-6))
        }

        model = build_model(X_train.shape[1], 1)

        # ✅ IMPORTANT: NORMAL LOSS (NOT focal)
        model.compile(
            optimizer='adam',
            loss='binary_crossentropy',
            metrics=['accuracy']
        )

        model.fit(
            X_train, y_train_bin,
            epochs=100,
            batch_size=64,
            class_weight=class_weights,
            verbose=1
        )

        # PREDICTION
        y_pred_prob = model.predict(X_test).flatten()

        # THRESHOLD TUNING
        best_f1 = 0
        best_th = 0.5

        for th in np.linspace(0.3, 0.7, 15):
            y_pred_bin = (y_pred_prob > th).astype(int)
            f1_temp = f1_score(y_test_bin, y_pred_bin, zero_division=0)

            if f1_temp > best_f1:
                best_f1 = f1_temp
                best_th = th

        print("Best Threshold:", best_th)

        y_pred_bin = (y_pred_prob > best_th).astype(int)

        f1 = f1_score(y_test_bin, y_pred_bin, zero_division=0)
        mae = mean_absolute_error(y_test, y_pred_prob)

        print("FINAL F1:", f1)
        print("MAE:", mae)

        model.save(f"{MODEL_PATH}/{APP}_classifier.h5")

        del model
        gc.collect()

        return {"F1": float(f1), "MAE": float(mae)}

    # =========================
    #  NORMAL APPLIANCES
    # =========================
    X_train, y_train, seq_train = load_data(APP, train_houses)
    X_test, y_test, seq_test = load_data(APP, test_houses)

    X_train = X_train[..., np.newaxis]
    X_test = X_test[..., np.newaxis]

    # USE SEQ2POINT FOR OTHERS ONLY
    seq_mean = np.mean(seq_train)
    seq_std = np.std(seq_train) + 1e-6

    seq_train = (seq_train - seq_mean) / seq_std
    seq_test = (seq_test - seq_mean) / seq_std

    seq_train = np.repeat(seq_train[:, np.newaxis], X_train.shape[1], axis=1)
    seq_test = np.repeat(seq_test[:, np.newaxis], X_test.shape[1], axis=1)

    seq_train = seq_train[..., np.newaxis]
    seq_test = seq_test[..., np.newaxis]

    X_train = np.concatenate([X_train, seq_train], axis=-1)
    X_test = np.concatenate([X_test, seq_test], axis=-1)

    # =========================
    # LABELS
    # =========================
    threshold = np.percentile(y_train, 50)

    y_train_bin = (y_train > threshold).astype(int)
    y_test_bin = (y_test > threshold).astype(int)

    print("Threshold:", threshold)
    print("ON ratio:", np.mean(y_train_bin))

    # =========================
    # SPLIT
    # =========================
    X_train, X_val, y_train_bin, y_val_bin = train_test_split(
        X_train, y_train_bin, test_size=0.2, random_state=42
    )

    # =========================
    # CLASS WEIGHTS
    # =========================
    classes = np.unique(y_train_bin)

    if len(classes) < 2:
        class_weights = None
    else:
        weights = compute_class_weight('balanced', classes=classes, y=y_train_bin)
        class_weights = {int(c): w for c, w in zip(classes, weights)}

    # =========================
    # MODEL
    # =========================
    model = build_model(X_train.shape[1], X_train.shape[2])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(1e-4),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    model.fit(
        X_train, y_train_bin,
        validation_data=(X_val, y_val_bin),
        epochs=100,
        batch_size=64,
        class_weight=class_weights,
        verbose=1
    )

    # =========================
    # THRESHOLD TUNING
    # =========================
    y_val_prob = model.predict(X_val).flatten()

    best_f1 = 0
    best_th = 0.5

    for th in np.linspace(0.2, 0.7, 30):
        pred = (y_val_prob > th).astype(int)
        f1 = f1_score(y_val_bin, pred, zero_division=0)

        if f1 > best_f1:
            best_f1 = f1
            best_th = th

    print("Best Threshold:", best_th)

    # =========================
    # TEST
    # =========================
    y_pred = model.predict(X_test).flatten()
    y_pred_bin = (y_pred > best_th).astype(int)

    f1 = f1_score(y_test_bin, y_pred_bin, zero_division=0)
    mae = mean_absolute_error(y_test, y_pred)

    print("FINAL F1:", f1)
    print("MAE:", mae)

    model.save(f"{MODEL_PATH}/{APP}_classifier.h5")

    del model
    gc.collect()

    return {"F1": float(f1), "MAE": float(mae)}

APP = "kettle"

result_kettle = train_classifier(APP)
print(result_kettle)

APP = "toaster"

result_toaster = train_classifier(APP)
print(result_toaster)

APP = "computer"

result_computer = train_classifier(APP)
print(result_computer)

APP = "lamp"

result_lamp = train_classifier(APP)
print(result_lamp)

# Load the final results from the JSON file
with open("/content/drive/MyDrive/FYP/results.json", "r") as f:
    results = json.load(f)

print("\n" + "="*35)
print("     FINAL CLASSIFIER RESULTS     ")
print("="*35)
# Using formatted headers to match the data spacing
print(f"{'Appliance':<12} | {'F1':<8} | {'MAE':<8}")
print("-" * 35)

for app, r in results.items():
    # .4f ensures 4 decimal places for consistency
    print(f"{app.capitalize():<12} | {r['F1']:<8.4f} | {r['MAE']:<8.4f}")

print("="*35)

model_filename = f"{MODEL_PATH}/{APP}_classifier.h5"
model.save(model_filename)
print(f"Model saved to: {model_filename}")

drive_path = f"/content/drive/MyDrive/FYP/models/{app}_classifier.h5"

    if os.path.exists(drive_path):
        # 2. Trigger the browser download to your PC
        print(f"Downloading {app} model to your PC...")
        files.download(drive_path)
    else:
        print(f"Error: {app} model not found at {drive_path}")

"""Convert to TensorFLow Lite"""

import tensorflow as tf
import os

MODEL_PATH = "/content/drive/MyDrive/FYP/models"

APPLIANCES = ["kettle", "toaster", "computer", "lamp"]

for APP in APPLIANCES:

    print(f"\n===== Converting: {APP} =====")

    h5_path = f"{MODEL_PATH}/{APP}_classifier.h5"
    tflite_path = f"{MODEL_PATH}/{APP}_classifier.tflite"

    if not os.path.exists(h5_path):
        print(f"Model not found: {h5_path}")
        continue

    # load model
    model = tf.keras.models.load_model(h5_path)

    # convert
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    tflite_model = converter.convert()

    # save
    with open(tflite_path, "wb") as f:
        f.write(tflite_model)

    print(f"Saved: {tflite_path}")

print("\nAll conversions done!")