# -*- coding: utf-8 -*-
"""Seq2Point.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yo5pO0d8yY2OqHiO-BeTeHTaPmdxWwOf
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.metrics import mean_absolute_error, f1_score

DATA_DIR = "/content/drive/MyDrive/FYP/phase3"
MODEL_PATH = "/content/drive/MyDrive/FYP/models"

APPLIANCES = ["toaster", "kettle", "computer", "lamp"]

train_houses = list(range(1, 17))
test_houses = list(range(17, 21))

print("GPU:", tf.config.list_physical_devices('GPU'))

def load_data(appliance, houses, max_samples=10000):
    X_all, y_all = [], []

    for file in os.listdir(DATA_DIR):
        if appliance not in file or not file.endswith(".npz"):
            continue

        house_id = int(file.split("_")[0].replace("house", ""))
        if house_id not in houses:
            continue

        path = os.path.join(DATA_DIR, file)
        data = np.load(path)

        X = data["X"][:max_samples]
        y = data["y"][:max_samples]

        X_all.append(X)
        y_all.append(y)

    if len(X_all) == 0:
        raise ValueError(f"No data found for {appliance}")

    return np.vstack(X_all), np.hstack(y_all)

def build_model(window_size):
    model = models.Sequential([
        layers.Conv1D(30, 10, activation='relu', input_shape=(window_size, 1)),
        layers.Conv1D(30, 8, activation='relu'),
        layers.Conv1D(40, 6, activation='relu'),
        layers.Conv1D(50, 5, activation='relu'),
        layers.Dropout(0.2),
        layers.Flatten(),
        layers.Dense(1024, activation='relu'),
        layers.Dense(1)
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss='mse'
    )

    return model

results = {}

for app in APPLIANCES:

    print("\n====================")
    print("TRAINING:", app)
    print("====================")

    # =========================
    # LOAD DATA
    # =========================
    X_train, y_train = load_data(app, train_houses)
    X_test, y_test = load_data(app, test_houses)

    print("Train:", X_train.shape, "Test:", X_test.shape)

    # =========================
    # RESHAPE
    # =========================
    X_train = X_train[..., np.newaxis]
    X_test = X_test[..., np.newaxis]

    # =========================
    # NORMALIZATION
    # =========================
    mean = np.mean(X_train)
    std = np.std(X_train) + 1e-6

    X_train = (X_train - mean) / std
    X_test = (X_test - mean) / std

    # =========================
    # BUILD MODEL
    # =========================
    model = build_model(X_train.shape[1])

    # =========================
    # TRAIN (100 EPOCHS - NO EARLY STOPPING)
    # =========================
    model.fit(
        X_train, y_train,
        epochs=100,
        batch_size=256,
        validation_split=0.1,
        verbose=1
    )

    # =========================
    # PREDICT
    # =========================
    y_pred = model.predict(X_test).flatten()

    # =========================
    # THRESHOLD (adaptive)
    # =========================
    threshold = np.percentile(y_train)

    # =========================
    # SMOOTHING
    # =========================
    y_pred_bin = (y_pred > threshold).astype(int)
    y_true_bin = (y_test > threshold).astype(int)

    # =========================
    # METRICS
    # =========================
    mae = mean_absolute_error(y_test, y_pred)
    f1 = f1_score(y_true_bin, y_pred_bin, zero_division=0)

    print("Threshold:", threshold)
    print("MAE:", mae)
    print("F1:", f1)

    results[app] = {
        "MAE": mae,
        "F1": f1
    }

    # =========================
    # SAVE MODEL
    # =========================
    model.save(f"{MODEL_PATH}/{app}_seq2point.h5")

# RECOMPUTE F1 (NO RETRAIN)

from sklearn.metrics import f1_score
import numpy as np

# NEW threshold (fixed)
threshold = np.mean(y_train)

# binarize
y_pred_bin = (y_pred > threshold).astype(int)
y_true_bin = (y_test > threshold).astype(int)

# recompute F1
f1 = f1_score(y_true_bin, y_pred_bin, zero_division=0)

print("New Threshold:", threshold)
print("Recomputed F1:", f1)

import os

for app in APPLIANCES:
    path = f"{MODEL_PATH}/{app}_seq2point.h5"

    if not os.path.exists(path):
        print(f"Missing model: {app}")
        continue

    print("\n==============================")
    print(f"MODEL SUMMARY: {app.upper()}")
    print("==============================")

    model = tf.keras.models.load_model(path, compile=False)
    model.summary()
    print("Total parameters:", model.count_params())

print("\n===== FINAL RESULTS =====")
print(f"{'Appliance':<12} {'MAE':<12} {'F1':<12}")
print("-" * 40)

for app, metrics in results.items():
    print(f"{app:<12} {metrics['MAE']:<12.4f} {metrics['F1']:<12.4f}")

import os

TFLITE_PATH = "/content/drive/MyDrive/FYP/tflite"
os.makedirs(TFLITE_PATH, exist_ok=True)

import tensorflow as tf
import os

APPLIANCES = ["toaster", "kettle", "computer", "lamp"]

MODEL_PATH = "/content/drive/MyDrive/FYP/models"
TFLITE_PATH = "/content/drive/MyDrive/FYP/tflite"

os.makedirs(TFLITE_PATH, exist_ok=True)

import os
import numpy as np
import tensorflow as tf
from sklearn.metrics import mean_absolute_error, f1_score
import warnings
import csv # --- NEW: Import the csv module ---

# Suppress warnings from f1_score when a class is not predicted
warnings.filterwarnings("ignore")

# --- Configuration ---
DATA_DIR = "/content/drive/MyDrive/FYP/phase3"
MODEL_PATH = "/content/drive/MyDrive/FYP/models"
# --- NEW: Define a path for the output results file ---
RESULTS_FILE_PATH = "/content/drive/MyDrive/FYP/optimized_results.csv"

APPLIANCES = ["toaster", "kettle", "computer", "lamp"]
train_houses = list(range(1, 17))
test_houses = list(range(17, 21))

# --- Data Loading Function (from your original code) ---
def load_data(appliance, houses, max_samples=10000):
    X_all, y_all = [], []
    for file in os.listdir(DATA_DIR):
        if appliance not in file or not file.endswith(".npz"):
            continue
        house_id = int(file.split("_")[0].replace("house", ""))
        if house_id not in houses:
            continue
        path = os.path.join(DATA_DIR, file)
        data = np.load(path)
        X = data["X"][:max_samples]
        y = data["y"][:max_samples]
        X_all.append(X)
        y_all.append(y)
    if len(X_all) == 0:
        raise ValueError(f"No data found for {appliance}")
    return np.vstack(X_all), np.hstack(y_all)

# --- Main Evaluation Loop ---
results = {}
print("Starting evaluation process (no training will occur)...")

for app in APPLIANCES:
    print(f"\n----- Evaluating: {app.upper()} -----")

    model_file = f"{MODEL_PATH}/{app}_seq2point.h5"
    if not os.path.exists(model_file):
        print(f"SKIPPING: Model file not found at {model_file}")
        continue

    # Step 1: Load Data
    X_train, _ = load_data(app, train_houses)
    X_test, y_test = load_data(app, test_houses)
    print(f"Loaded data for {app}.")

    # Step 2: Normalize Test Data
    mean = np.mean(X_train)
    std = np.std(X_train) + 1e-6
    X_test_normalized = (X_test - mean) / std
    X_test_reshaped = X_test_normalized[..., np.newaxis]

    # Step 3: Load the Pre-Trained Model
    model = tf.keras.models.load_model(model_file, compile=False)
    print(f"Successfully loaded model: {os.path.basename(model_file)}")

    # Step 4: Make Predictions
    y_pred = model.predict(X_test_reshaped).flatten()

    # Step 5: Smooth the Predictions
    kernel = np.ones(5) / 5
    y_pred_smooth = np.convolve(y_pred, kernel, mode='same')

    # Step 6: Find the Optimal Threshold
    print("Searching for the optimal F1 score threshold...")
    best_f1 = 0
    best_threshold = 0
    for threshold_iter in np.arange(0.0, 1.0, 0.01):
        y_pred_bin_eval = (y_pred_smooth > threshold_iter).astype(int)
        y_true_bin_eval = (y_test > threshold_iter).astype(int)
        f1_eval = f1_score(y_true_bin_eval, y_pred_bin_eval)
        if f1_eval > best_f1:
            best_f1 = f1_eval
            best_threshold = threshold_iter

    # Step 7: Calculate Final Metrics
    mae = mean_absolute_error(y_test, y_pred)
    f1_optimized = best_f1

    print(f"Evaluation Complete for {app}:")
    print(f"  - Optimal Threshold Found: {best_threshold:.2f}")
    print(f"  - MAE: {mae:.4f}")
    print(f"  - Optimized F1 Score: {f1_optimized:.4f}")

    # --- NEW: Store the best_threshold along with the other metrics ---
    results[app] = {
        "MAE": mae,
        "F1": f1_optimized,
        "Threshold": best_threshold
    }

# --- Final Summary Table ---
print("\n================ FINAL OPTIMIZED RESULTS ================")
print(f"{'Appliance':<12} {'MAE':<12} {'F1':<12} {'Threshold':<12}")
print("-" * 50)

if not results:
    print("No models were evaluated. Check model paths.")
else:
    for app, metrics in results.items():
        print(f"{app:<12} {metrics['MAE']:<12.4f} {metrics['F1']:<12.4f} {metrics['Threshold']:<12.2f}")

    # Calculate and print averages
    if len(results) > 0:
        avg_mae = np.mean([m['MAE'] for m in results.values()])
        avg_f1 = np.mean([m['F1'] for m in results.values()])
        print("\n===== AVERAGE =====")
        print(f"Avg MAE: {avg_mae:.4f}")
        print(f"Avg F1 : {avg_f1:.4f}")

# --- NEW: Save results to a CSV file ---
# =========================================================
if results: # Only run if there are results to save
    print(f"\nSaving results to CSV file...")
    try:
        with open(RESULTS_FILE_PATH, 'w', newline='') as csvfile:
            # Define the header for the CSV file
            fieldnames = ['Appliance', 'MAE', 'F1', 'Optimal_Threshold']
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

            # Write the header
            writer.writeheader()

            # Write the data for each appliance
            for app, metrics in results.items():
                writer.writerow({
                    'Appliance': app,
                    'MAE': f"{metrics['MAE']:.4f}",
                    'F1': f"{metrics['F1']:.4f}",
                    'Optimal_Threshold': f"{metrics['Threshold']:.2f}"
                })

            # Write the average values as the last row
            writer.writerow({
                'Appliance': 'AVERAGE',
                'MAE': f"{avg_mae:.4f}",
                'F1': f"{avg_f1:.4f}",
                'Optimal_Threshold': 'N/A'
            })
        print(f"Successfully saved results to: {RESULTS_FILE_PATH}")
    except Exception as e:
        print(f"Error saving file: {e}")
# =========================================================